RHAIENG-2042: chore(base-images): use AIPCC-style scripting instead of scl base to add `s390x` architecture to odh-base-image-cpu-py312-c9s (#2690)
```
[2/3] STEP 1/10: FROM quay.io/opendatahub/odh-base-image-cpu-py312-c9s:latest AS cpu-base
Trying to pull quay.io/opendatahub/odh-base-image-cpu-py312-c9s:latest...
Error: creating build container: unable to copy from source docker://quay.io/opendatahub/odh-base-image-cpu-py312-c9s:latest: choosing an image from manifest list docker://quay.io/opendatahub/odh-base-image-cpu-py312-c9s:latest: no image found in manifest list for architecture "s390x", variant "", OS "linux"
```