fix(codeserver): the builder rpm stage also needs to have ubi9.repo file installed if missing on aipcc
```
+ dnf install -y jq libtool gcc-toolset-13
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".
subprocess exited with status 1
subprocess exited with status 1
Error: building at STEP "RUN ./get_code_server_rpm.sh && touch /tmp/control": exit status 1
```