NO-JIRA: fix(codeserver): build needs rsync at some point which is absent from aipcc bases
```
npm notice package-lock.json has been renamed to npm-shrinkwrap.json
npm notice package-lock.json has been renamed to npm-shrinkwrap.json
npm notice package-lock.json has been renamed to npm-shrinkwrap.json
./ci/lib.sh: line 44: rsync: command not found
subprocess exited with status 127
subprocess exited with status 127
Error: building at STEP "RUN ./get_code_server_rpm.sh && touch /tmp/control": exit status 127
```