NO-JIRA: add `TARGETARCH` argument on top of various CUDA Dockerfiles for multi-architecture support (#2334)
```
[2025-09-05T16:51:38,163673637+00:00] Prepare system (architecture: x86_64)
[2025-09-05T16:51:42,271864338+00:00] Setup prefetched
Error: parsing reference "cuda-base-": invalid reference format
```

(cherry picked from commit bc55b3a89df81710940003d1e2856adcbb9dc3f9)