fix(deps): fix merge error in jupyter/datascience/ubi9-python-3.12/pylock.toml (#1577)
```
error: Not a valid `pylock.toml` file: ./pylock.toml
  Caused by: TOML parse error at line 3088, column 1
     |
3088 | marker = "platform_machine != 's390x'"
     | ^^^^^^
duplicate key
subprocess exited with status 2
```