try to install with uv
```
  × No solution found when resolving dependencies:
  ╰─▶ Because there is no version of certifi==2025.1.31 and you require
      certifi==2025.1.31, we can conclude that your requirements are
      unsatisfiable.

      hint: `certifi` was found on https://download.pytorch.org/whl/cu121, but
      not at the requested version (certifi==2025.1.31). A compatible version
      may be available on a subsequent index (e.g., https://pypi.org/simple).
      By default, uv will only consider versions that are published on the
      first index that contains a given package, to avoid dependency confusion
      attacks. If all indexes are equally trusted, use `--index-strategy
      unsafe-best-match` to consider all versions from all indexes, regardless
      of the order in which they were defined.
```

When installing as `USER 1001` in /opt/app-root

```
Using Python 3.11.9 environment at: /opt/app-root
error: Permission denied (os error 13) at path "/opt/app-root/.tmpQEqqyQ"
```

believe we should _not_ enable
https://docs.astral.sh/uv/reference/settings/#compile-bytecode
https://github.com/astral-sh/uv/issues/6493
```
UV_COMPILE_BYTECODE=1
--compile-bytecode
```

uv has bug installing tensorflow
https://github.com/astral-sh/uv/issues/12092