increase `swap_size_mb` to 16GB in `gha_lvm_overlay.sh` to prevent memory issues during codeserver build (#2356)
turns out 16GB is probably overkill; the 256MB was not sufficient,
given the OOM kill, but I was later adding vm mem even when the problem
was insufficient nodejs heap limit, and not vm memory

```
./ci/build/build-vscode.sh: line 38:  9100 Killed                  npm run gulp "vscode-reh-web-linux-x64${MINIFY:+-min}"
Error: building at STEP "RUN ./get_code_server_rpm.sh && touch /tmp/control": while running runtime: exit status 137
ERROR:sandbox.py:Failed to execute process, see errors logged above ^^^
```