RHAIENG-2111: build(trustyai): add missing pillow requirements and other python requirements
```
The headers or library files could not be found for jpeg,
a required dependency when compiling Pillow from source.
Please see the install instructions at:
   https://pillow.readthedocs.io/en/latest/installation/basic-installation.html
  × Failed to build `/tmp/tmp.mHgTyZTiW2/Pillow`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `backend.build_wheel` failed (exit status: 1)
      hint: This usually indicates a problem with the package or the build
      environment.
subprocess exited with status 2
```

```
            Could not find directory of OpenSSL installation, and this `-sys`
          crate cannot
            proceed without this knowledge. If OpenSSL is installed and this crate
          had
            trouble finding it,  you can set the `OPENSSL_DIR` environment
          variable for the
            compilation process.

            Make sure you also have the development packages of openssl installed.
            For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

            If you're in a situation where you think the directory *should* be
          found
            automatically, please open a bug at
          https://github.com/sfackler/rust-openssl
            and include information about your system as well as this message.
...
        warning: build failed, waiting for other jobs to finish...
        💥 maturin failed
          Caused by: Failed to build a native library through cargo
          Caused by: Cargo build finished with "exit status:
        101": `env -u CARGO PYO3_BUILD_EXTENSION_MODULE="1"
        PYO3_ENVIRONMENT_SIGNATURE="cpython-3.12-64bit"
        PYO3_PYTHON="/root/.cache/uv/builds-v0/.tmpsjsmaI/bin/python"
        PYTHON_SYS_EXECUTABLE="/root/.cache/uv/builds-v0/.tmpsjsmaI/bin/python"
        "cargo" "rustc" "--profile" "release" "--features" "pyo3/abi3-py37"
        "--message-format" "json-render-diagnostics" "--locked" "--manifest-path"
        "/root/.cache/uv/sdists-v9/index/c2c553577285dd6f/cryptography/43.0.3/0S5Vw6G2gpWxT0EJkPki9/src/src/rust/Cargo.toml"
        "--lib"`
        Error: command ['maturin', 'pep517', 'build-wheel', '-i',
        '/root/.cache/uv/builds-v0/.tmpsjsmaI/bin/python', '--compatibility',
        'off'] returned non-zero exit status 1

        hint: This usually indicates a problem with the package or the build
        environment.
  subprocess exited with status 1
```

```
+ uv pip install /wheelsdir/pillow-11.3.0-cp312-cp312-manylinux_2_34_ppc64le.whl /wheelsdir/pyarrow-20.0.0-cp312-cp312-linux_ppc64le.whl /wheelsdir/torch-2.7.1-cp312-cp312-linux_ppc64le.whl accelerate --cache-dir /root/.cache/uv
...
  × No solution found when resolving dependencies:
  ╰─▶ Because numpy==2.3.4 has no wheels with a matching platform tag (e.g.,
      `manylinux_2_34_ppc64le`) and only numpy==2.3.4 is available, we can
      conclude that numpy==2.3.4 cannot be used.
      And because accelerate==1.10.1 depends on numpy==2.3.4 and only the
      following versions of accelerate are available:
          accelerate==1.10.1
          accelerate==1.11.0
      we can conclude that accelerate<1.11.0 cannot be used. (1)
      Because numpy==2.3.4 has no wheels with a matching platform tag (e.g.,
      `manylinux_2_34_ppc64le`) and only numpy==2.3.4 is available, we can
      conclude that numpy==2.3.4 cannot be used.
      And because accelerate==1.11.0 depends on numpy==2.3.4, we can conclude
      that accelerate==1.11.0 cannot be used.
      And because we know from (1) that accelerate<1.11.0 cannot be used, we
      can conclude that all versions of accelerate cannot be used.
      And because you require accelerate, we can conclude that your
      requirements are unsatisfiable.
      hint: Wheels are available for `numpy` (v2.3.4) on the following
      platforms: `linux_aarch64`, `linux_x86_64`
subprocess exited with status 1
```

(cherry picked from commit 6f83dd5a36e97c1ec4d8f45207a91f1d11e8ef45)