RHAIENG-948: fix(jupyter datascience on IBM/Power): build failure due to AIPCC base (missing curl and openssl -devel packages) and AIPCC wheels (some prereqs are missing) (#2678)
* RHAIENG-948: fix(ppc): build failure due to missing curl

add `libcurl-devel` to build dependencies for `ppc64le` and `s390x` in pyarrow and onnx builds

```
  -- Building AWS C++ SDK from source
  CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
```

* RHAIENG-948: fix(ppc): build failure due to missing openssl

add `libcurl-devel` to build dependencies for `ppc64le` and `s390x` in pyarrow and onnx builds

```
  -- Configuring done (1.8s)
  -- Generating done (0.1s)
  CMake Error at cmake_modules/ThirdpartyToolchain.cmake:5282 (set_property):
    The link interface of target "AWS::aws-c-cal" contains:

      OpenSSL::Crypto

    but the target was not found.  Possible reasons include:

      * There is a typo in the target name.
      * A find_package call is missing for an IMPORTED target.
      * An ALIAS target is missing.
```

* RHAIENG-948: fix(ppc): build failure due to missing cython in aipcc wheel index

```
+ pip install --no-cache-dir -r requirements-build.txt

Looking in indexes: https://console.redhat.com/api/pypi/public-rhai/rhoai/3.0/cpu-ubi9/simple/

Ignoring oldest-supported-numpy: markers 'python_version < "3.9"' don't match your environment

ERROR: Could not find a version that satisfies the requirement cython>=0.29.31 (from versions: none)

ERROR: No matching distribution found for cython>=0.29.31
```

* RHAIENG-948: fix(ppc): build failure due to missing numpy in aipcc wheel index

```
+ pip install --no-cache-dir -r requirements.txt
  Looking in indexes: https://console.redhat.com/api/pypi/public-rhai/rhoai/3.0/cpu-ubi9/simple/
  ERROR: Could not find a version that satisfies the requirement numpy>=1.22 (from versions: none)
  ERROR: No matching distribution found for numpy>=1.22
  subprocess exited with status 1
```

* RHAIENG-948: fix(ppc): build failure due to missing protobuf>=4.25.1 in aipcc wheel index

```
+ pip wheel . -w /root/onnx_wheel
...
        ERROR: Could not find a version that satisfies the requirement protobuf>=4.25.1 (from versions: none)
        ERROR: No matching distribution found for protobuf>=4.25.1
        [end of output]
```

* RHAIENG-948: fix(ppc): build failure due to missing numpy>=1.16.6 in aipcc wheel index

```
+ pip install --no-cache-dir /tmp/wheels/pyarrow-17.0.0-cp312-cp312-linux_ppc64le.whl
Looking in indexes: https://console.redhat.com/api/pypi/public-rhai/rhoai/3.0/cpu-ubi9/simple/
Processing /tmp/wheels/pyarrow-17.0.0-cp312-cp312-linux_ppc64le.whl
INFO: pip is looking at multiple versions of pyarrow to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement numpy>=1.16.6 (from pyarrow) (from versions: none)
ERROR: No matching distribution found for numpy>=1.16.6
```

* RHOAIENG-32541: chore(jupyter/datascience): add `subscription-manager refresh` step to CPU Dockerfile for base image

https://issues.redhat.com/browse/RHOAIENG-32541

* RHAIENG-948: fix(ppc): build failure due to missing cryptography build dependencies in aipcc wheel index

```
  × Failed to download and build `cryptography==43.0.3`
  ├─▶ Failed to resolve requirements from `build-system.requires`
  ├─▶ No solution found when resolving: `maturin>=1, <2`, `cffi>=1.12
  │   ; platform_python_implementation != 'PyPy'`, `setuptools!=74.0.0,
  │   !=74.1.0, !=74.1.1, !=74.1.2, !=74.1.3, !=75.0.0, !=75.1.0, !=75.2.0`
  ╰─▶ Because only maturin==1.9.6 is available and maturin==1.9.6 has no
      wheels with a matching platform tag (e.g., `manylinux_2_34_ppc64le`), we
      can conclude that maturin==1.9.6 cannot be used.
      And because you require maturin==1.9.6, we can conclude that your
      requirements are unsatisfiable.

      hint: Wheels are available for `maturin` (v1.9.6) on the following
      platforms: `linux_aarch64`, `linux_x86_64`
```

* RHAIENG-948: fix(ppc): build failure due to missing zlib-devel to build pillow

```

      line 20, in run_setup
          return super().run_setup(setup_script)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File
      "/tmp/.tmpoAXecA/builds-v0/.tmpeN0QF3/lib64/python3.12/site-packages/setuptools/build_meta.py",
      line 317, in run_setup
          exec(code, locals())
        File "<string>", line 1108, in <module>
      RequiredDependencyException:
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
```

* RHAIENG-948: fix(ppc): build failure due to missing libjpeg-turbo-devel to build pillow

```
        The headers or library files could not be found for jpeg,
        a required dependency when compiling Pillow from source.

        Please see the install instructions at:

        https://pillow.readthedocs.io/en/latest/installation/basic-installation.html
```

* RHAIENG-948: fix(ppc): build failure due to missing openssl-devel to build maturin

```
        Could not find openssl via pkg-config:
        pkg-config exited with status code 1
        > PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
      PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags openssl
        The system library `openssl` required by crate `openssl-sys` was not
      found.
        The file `openssl.pc` needs to be installed and the PKG_CONFIG_PATH
      environment variable must contain its parent directory.
        PKG_CONFIG_PATH contains the following:
            - /usr/local/lib/pkgconfig/
        HINT: you may need to install a package such as openssl, openssl-dev
      or openssl-devel.
...
        Could not find directory of OpenSSL installation, and this `-sys`
      crate cannot
        proceed without this knowledge. If OpenSSL is installed and this crate
      had
        trouble finding it,  you can set the `OPENSSL_DIR` environment
      variable for the
        compilation process.
        Make sure you also have the development packages of openssl installed.
        For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.
...
      warning: build failed, waiting for other jobs to finish...
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status:
```

* RHAIENG-948: fix(ppc): build failure due to missing fortran to build scikit-learn

```
  × Failed to download and build `scikit-learn==1.7.2`
  ├─▶ Failed to install requirements from `build-system.requires`
  ├─▶ Failed to build `scipy==1.16.3`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `mesonpy.build_wheel` failed (exit status: 1)
      [stdout]
      + meson setup
...
      ../meson.build:88:0: ERROR: Unknown compiler(s): [['gfortran'],
      ['flang-new'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'],
      ['ifx'], ['g95']]
      The following exception(s) were encountered:
      Running `gfortran --help` gave "[Errno 2] No such file or directory:
      'gfortran'"
```