NO-JIRA: fix(codeserver): build needs envsubst at some point which is absent from aipcc bases
```
done (release-packages/code-server-4.98.0-linux-arm64)
./ci/build/build-packages.sh: line 57: envsubst: command not found
Error: building at STEP "RUN ./get_code_server_rpm.sh && touch /tmp/control": while running runtime: exit status 127
```