fix(codeserver/Dockerfile): with the AIPCC ppc64le base, installing `patch` explicitly is required, amd64 and arm64 bases already seem to have it
```
+ patch -p1
./get_code_server_rpm.sh: line 65: patch: command not found
subprocess exited with status 127
subprocess exited with status 127
Error: building at STEP "RUN ./get_code_server_rpm.sh && touch /tmp/control": exit status 127
```