RHAIENG-287: fix(tests/llmcompressor): create missing `kustomization.yaml` (#2602)
```
# Deploying notebook from runtimes/pytorch/llmcompressor/ubi9-python-3.12/kustomize/base directory...

arg=ghcr.io/opendatahub-io/notebooks/workbench-images bin/yq e -i '.images[].newName = strenv(arg)' runtimes/pytorch/llmcompressor/ubi9-python-3.12/kustomize/base/kustomization.yaml
arg=runtime-cuda-pytorch-llmcompressor-ubi9-python-3.12-_8adf444fa4f489cd5b34d7fce14f94795812393b bin/yq e -i '.images[].newTag = strenv(arg)' runtimes/pytorch/llmcompressor/ubi9-python-3.12/kustomize/base/kustomization.yaml
bin/kubectl apply -k runtimes/pytorch/llmcompressor/ubi9-python-3.12/kustomize/base
+ arg=ghcr.io/opendatahub-io/notebooks/workbench-images
+ bin/yq e -i '.images[].newName = strenv(arg)' runtimes/pytorch/llmcompressor/ubi9-python-3.12/kustomize/base/kustomization.yaml
Error: stat runtimes/pytorch/llmcompressor/ubi9-python-3.12/kustomize/base/kustomization.yaml: no such file or directory
```