fix(trustyai): compilation failures reported by testops
* fix(trustyai): missing expecttest dependency in some IBM p/z compilation, enable upstream pypi to fix

```
ERROR: Could not find a version that satisfies the requirement expecttest>=0.3.0 (from versions: none)
ERROR: No matching distribution found for expecttest>=0.3.0
subprocess exited with status 1
```

* fix(trustyai): build failure in pytorch compilation on ppc64le

https://redhat-internal.slack.com/archives/C07ANR2U56C/p1771520858856879

The -r requirements inclusion was added in https://github.com/pytorch/pytorch/pull/158111, and it looks to be a new Torch 2.9 addition.

* install auditwheel from pypi, same change needed for codeserver later