Remove requirments-elyra.txt from the code base (#761)
* Remove requirments-elyra.txt from the code base

* changes that were requested in review

* also remove volumeMounts from pod.yaml files

* fix linter errors

./runtimes/rocm-tensorflow/ubi9-python-3.11/kustomize/base/kustomization.yaml
  Error: 11:1 [empty-lines] too many blank lines (1 > 0)

./runtimes/tensorflow/ubi9-python-3.11/kustomize/base/kustomization.yaml
  Error: 11:1 [empty-lines] too many blank lines (1 > 0)

and wrongly intended line in Makefile, that's not linted automatically

* fix missing comment starter # marks in `utils/requirements-elyra.txt`

without it, pip would error out on this invalid requirements file

---------

Co-authored-by: Jiri Daněk <jdanek@redhat.com>