NO-JIRA: tests(browser/): update dependencies in pnpm-lock.yaml
Updated multiple dependencies to their latest versions, including Playwright, TypeScript, and Testcontainers.

```
+ pnpm exec playwright test
Error: Cannot find module '/mnt/node_modules/testcontainers/build/wait-strategies/http-wait-strategy' imported from /mnt/tests/codeserver.spec.ts
Did you mean to import "testcontainers/build/wait-strategies/http-wait-strategy.js"?
```

```
    Error: browserType.launch: Executable doesn't exist at /ms-playwright/chromium_headless_shell-1169/chrome-linux/headless_shell
    ╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to 1.52.0. ║
    ║ Please update docker image as well.                                  ║
    ║ -  current: mcr.microsoft.com/playwright:v1.48.1-noble               ║
    ║ - required: mcr.microsoft.com/playwright:v1.52.0-noble               ║
    ║                                                                      ║
    ║ <3 Playwright Team                                                   ║
    ╚══════════════════════════════════════════════════════════════════════╝
```