NO-JIRA: fix update-commit-latest-env.py to work with multiarch manifests (#2107)
```
ERROR: Skopeo command failed for quay.io/rhoai/odh-workbench-jupyter-trustyai-cpu-py312-rhel9@sha256:c0482a03d45fbe3a2acff4e9d583830d54324e939ba1bb19472af4f29d5e233f with exit code 1.
ERROR: Stderr: time="2025-08-22T14:34:19+02:00" level=fatal msg="Error parsing manifest for image: choosing image instance: no image found in image index for architecture \"arm64\", variant \"v8\", OS \"darwin\""
```

Needed to work with the quay.io/rhoai workbench images from rhds.