RHAIENG-2111: chore(trustyai): enable pypi to get access to required build dependencies (#1732)
* expecttest not present

* cmake, auditwheel, and some build-deps are not present

* uv for ibm arches is not present in 3.0 aipcc index

```
  + pip install --no-cache-dir uv
  Looking in indexes: https://console.redhat.com/api/pypi/public-rhai/rhoai/3.0/cpu-ubi9/simple/
  ERROR: Could not find a version that satisfies the requirement uv (from versions: none)
```

* cython is a build dependency for pandas

```
   Downloading scipy
     Building pandas==1.5.3
    × Failed to download and build `pandas==1.5.3`
    ├─▶ Failed to resolve requirements from `build-system.requires`
    ├─▶ No solution found when resolving: `setuptools>=51.0.0`, `wheel`,
    │   `cython>=0.29.32, <3`, `oldest-supported-numpy>=2022.8.16`
    ╰─▶ Because only cython>=3.0.12 is available and you require
        cython>=0.29.32,<3, we can conclude that your requirements are
        unsatisfiable.
  subprocess exited with status 1
```