RHAIENG-1512: fix(ROCm/TensorFlow) onnx 1.19.0 incompatibility AttributeError: module 'ml_dtypes' has no attribute 'float4_e2m1fn'
```
File /opt/app-root/lib64/python3.12/site-packages/onnx/_mapping.py:104

AttributeError: module 'ml_dtypes' has no attribute 'float4_e2m1fn'
```

* https://github.com/jax-ml/ml_dtypes/pull/181

It seems that ml-types only added this in 0.5.0 but in our tf rocm images it resolves to 0.4.1.

```
/Users/jdanek/IdeaProjects/notebooks/runtimes/rocm-tensorflow/ubi9-python-3.12
  × No solution found when resolving dependencies:
  ╰─▶ Because tensorflow-rocm==2.17.0 depends on ml-dtypes>=0.3.1,<0.5.0 and ml-dtypes>=0.5.0, we can conclude that tensorflow-rocm==2.17.0 cannot be used.
      And because only tensorflow-rocm==2.17.0 is available and rocm-tensorflow-ubi9-python-3-12 depends on tensorflow-rocm, we can conclude that your requirements are unsatisfiable.
```

That means we cannot upgrade ml-dtypes, therefore we have to downgrade onnx

* https://github.com/onnx/onnx/pull/7089