NO-JIRA: install python according to `.python-version` file (#2764)
```
Run bash ci/generate_code.sh
+ uv --version
ci/generate_code.sh: line 4: uv: command not found
+ pip install uv==0.9.6
Defaulting to user installation because normal site-packages is not writeable
Collecting uv==0.9.6
  Downloading uv-0.9.6-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Downloading uv-0.9.6-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (21.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.4/21.4 MB 137.9 MB/s eta 0:00:00
Installing collected packages: uv
Successfully installed uv-0.9.6
+ python3 scripts/dockerfile_fragments.py
  File "/home/runner/work/notebooks/notebooks/scripts/dockerfile_fragments.py", line 69
    "upgrade first to avoid fixable vulnerabilities": textwrap.dedent(ntb.process_template_with_indents(rt"""
                          ^^^
SyntaxError: invalid syntax
Error: Process completed with exit code 1.
```

https://github.com/opendatahub-io/notebooks/actions/runs/20073940406/job/57583254538?pr=2760