NO-JIRA: chore(scripts/pylocks_generator.sh): regenerate locks with `--universal` option enabled (#2768)
This is due to changes in latest uv that have caused rhds builds to fail with

```
+ uv pip install --strict --no-deps --no-cache --no-config --no-progress --verify-hashes --compile-bytecode --index-strategy=unsafe-best-match --requirements=./pylock.toml
warning: The `--pylock` option is experimental and may change without warning. Pass `--preview-features pylock` to disable this warning.
Using Python 3.12.9 environment at: /opt/app-root
error: Package `ray` can't be installed because it doesn't have a source distribution or wheel for the current platform
hint: You're on Linux (`manylinux_2_34_aarch64`), but `ray` (v2.47.1) only has wheels for the following platform: `manylinux2014_x86_64`; consider adding "sys_platform == 'linux' and platform_machine == 'aarch64'" to `tool.uv.required-environments` to ensure uv resolves to a version with compatible wheels
```

and other such fan messages when only x86-64 gets resolved.